### ISSUE TITLE
Bug at IBluetoothNavigator.GetAvailability()

### ISSUE THREAD

**Issue by Domivan** [valerii-sovytskyi/Blazor.Bluetooth#1]
While IBluetoothNavigator.GetAvailability():
System.Exception: Could not find 'ble.getAvailability' ('ble' was undefined).
Error: Could not find 'ble.getAvailability' ('ble' was undefined).

**Comment by valerii-sovytskyi** [comment]
Hi @Domivan, thanks for your interest in this library.
As this technology is really new to us, not all browsers are supporting all the features.
Please check this documentation to see if your browser version support **Bluetooth getAvailability** and I think **Bluetooth** at all.
https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth#browser_compatibility

Please let me know your browser and version so I can check it!

(Also, you should notice that features are added so frequently that even not all the documentation is up to date, I faced with advertisements feature that this doc didn't support, so I found the answer in Python docs)

**Comment by valerii-sovytskyi** [comment]
I'm updating the solution to throw BluetoothUnavailableException, in case the browser can't see **navigator.Bluetooth**. 
But the message is different than yours, I guess this is not an issue. Feels like your solution is not seen **JSInteropt.js** or its content.

The thing is that **IBluetoothNavigator** takes in a constructor **IJSRuntime**, not sure but if you have rewritten yours  **IJSRuntime** maybe it uses your javascript code instead.

Anyway, you should check if you added this ref in your index.html

`<script src="_content/Blazor.Bluetooth/JSInterop.js"></script>`

And called this code in Program.cs

`builder.Services.AddBluetoothNavigator();`

If nothing helps, I would like to see an example of your code.

**Comment by valerii-sovytskyi** [comment]
Hi @Domivan, thanks for your interest in this library.

Please check if you added in your **wwwrooot/index.html** ```<script src="_content/Blazor.Bluetooth/JSInterop.js"></script>```

You can check the example code if you have any questions.

If it does not help you, please let me know!

**Comment by valerii-sovytskyi** [comment]
I'm closing this issue, as this is most probably the fix

**Comment by Domivan** [comment]
Good afternoon!
In webassembly everything works if you put the script
<script src="_content/Blazor.Bluetooth/JSInterop.js"></script>
after
<script src="_framework/blazor.webassembly.js"></script>
Is server-side still have error
![image](https://user-images.githubusercontent.com/4354000/189876726-a9c5e561-f7ec-422a-95e7-c7408d793e45.png)

just look simple BlazorApp1 server-side template 
https://github.com/Domivan/BlazorApp1

**Comment by valerii-sovytskyi** [comment]
Hi @Domivan,
I actually didn't test Server application before.
But today I did so. I don't understand why Blazor.Server does not see the javascript file from the NuGet, but it should. I tried to find any information on the internet but had no luck.

As the last thing I can do is to upload a javascript file on the internet I decided to use a script from the test blazor web assembly client.

So, you should just add this script
`<script src="https://blazorbluetooth.azurewebsites.net/_content/Blazor.Bluetooth/JSInterop.js"></script>`

I will fix your issue, but it means I need to update the test server all the time.
If anybody else knows how to solve it by getting the js file from the Nuget, please let me know.

@Domivan let me know if it solved your issue.
Thanks!

**Comment by valerii-sovytskyi** [comment]
@Domivan version 1.0.4 is really works with <script src="_content/Blazor.Bluetooth/JSInterop.js"></script>
I will investigate what went wrong with the latest versions
Thanks for noticing.

**Comment by valerii-sovytskyi** [comment]
@Domivan finally I found the issue, thanks for the help, I checked the changes between 1.0.4 and 1.0.5, and small refactoring broke the NuGet for Blazor Server App.
Now, please use 1.0.5.5, this should fix this issue

**Comment by Domivan** [comment]
Thanks a lot! You are super, your library is very convenient.
